"use client";
import {useEffect,useState} from "react";
import {ArrowDownRight,ArrowUpRight,Code2,Menu,X} from "lucide-react";
import type {Project} from "./project-types";
export default function Portfolio(){const[p,setP]=useState<Project[]>([]),[open,setOpen]=useState(false);useEffect(()=>{fetch('/api/projects',{cache:'no-store'}).then(async r=>{if(!r.ok)return [];const data=await r.json();return Array.isArray(data)?data:[]}).then(setP).catch(()=>setP([]))},[]);return <main>
<header className="nav"><a className="brand" href="#top">LYBERCH<span>_</span></a><nav className={open?'nav-links open':'nav-links'}><a href="#work" onClick={()=>setOpen(false)}>Work</a><a href="#about" onClick={()=>setOpen(false)}>About</a><a href="#contact" onClick={()=>setOpen(false)}>Contact</a></nav><div className="nav-right"><a className="admin-link" href="/admin/login">Admin</a><button className="menu-btn" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></div></header>
<section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><i/> AVAILABLE FOR SELECT PROJECTS</p><h1>Digital work<br/><em>with intent.</em></h1><p className="hero-text">I design and build sharp, fast digital experiences where thoughtful interfaces meet reliable engineering.</p><div className="hero-actions"><a className="button" href="#work">Explore work <ArrowDownRight size={17}/></a><a className="text-link" href="#contact">Start a conversation</a></div></div><div className="hero-card"><div className="card-grid"/><div className="terminal"><div className="term-top"><span/><span/><span/><b>lyberch.dev</b></div><div className="term-body"><p><b className="green">$</b> whoami</p><p className="term-output">designer + developer</p><p><b className="green">$</b> stack</p><p className="term-output">Next.js · TypeScript · UI</p><p><b className="green">$</b> status</p><p className="term-output"><span className="pulse"/> ready_to_build<span className="cursor">▋</span></p></div></div></div></section>
<section className="marquee"><span>WEB DEVELOPMENT</span><b>✦</b><span>UI DESIGN</span><b>✦</b><span>DIGITAL PRODUCTS</span><b>✦</b></section>
<section className="section" id="work"><div className="section-head"><div><p className="label">01 / SELECTED WORK</p><h2>Things I&apos;ve built.</h2></div><span className="count">{String(p.length).padStart(2,'0')} projects</span></div><div className="projects">{p.filter(x=>x.published!==false).map((x,i)=><a className="project" href={`/project/${x.id}`} key={x.id}><div className="project-image"><img src={x.image} alt={x.title}/><span className="project-index">{String(i+1).padStart(2,'0')}</span><span className="view-project">View <ArrowUpRight size={16}/></span></div><div className="project-info"><div><h3>{x.title}</h3><p>{x.description}</p><div className="tags">{x.tags.map(t=><span key={t}>{t}</span>)}</div></div><span className="round-arrow"><ArrowUpRight/></span></div></a>)}</div></section>
<section className="about section" id="about"><div><p className="label">02 / ABOUT</p><h2>Design-minded.<br/><em>Code-driven.</em></h2></div><div className="about-copy"><p>I bridge the gap between design and engineering. From the first wireframe to the last line of production code, I care about the details that make a product feel simple, intentional and alive.</p><div className="skills"><span>01 — Product UI</span><span>02 — Frontend Development</span><span>03 — Design Systems</span><span>04 — Creative Direction</span></div></div></section>
<section className="contact section" id="contact"><p className="label">03 / CONTACT</p><h2>Have an idea?<br/><em>Let&apos;s make it real.</em></h2><a className="contact-email" href="mailto:lyberch@proton.me">lyberch@proton.me <ArrowUpRight/></a></section><footer><span>© {new Date().getFullYear()} LYBERCH</span><span>WEB DEVELOPMENT / UI DESIGN</span><a href="/admin/login"><Code2 size={13}/> ADMIN</a></footer></main>}
